<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.4.9</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>ai.aitia.arrowhead</groupId>
	<artifactId>qos-test-suite</artifactId>
	<version>1.0.1</version>
	<packaging>pom</packaging>
	<name>ah5-aitia-qos-test-suite</name>
	<description>Simple applications for testing AH5 default QoS evaluator</description>

	<url>https://github.com/Aitia-IIOT/ah5-aitia-qos-test-suite</url>
	<licenses>
		<license>
	     	<name>Eclipse Public License - v 2.0</name>
	     	<url>https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt</url>
	   </license>
	</licenses>
	
	<properties>
		<java.version>21</java.version>
	</properties>

	<modules>
		<module>qos-shared-resources</module>
		<module>qos-cpu-test-consumer</module>
		<module>qos-cpu-test-provider</module>
	</modules>

	<dependencies>
		<dependency>
			<groupId>ai.aitia.arrowhead</groupId>
			<artifactId>arrowhead-app-common</artifactId>
			<version>1.0.3</version>
		</dependency>
		<dependency>
			<groupId>eu.arrowhead</groupId>
			<artifactId>arrowhead-data-transfer-objects</artifactId>
			<version>5.2.2</version>
		</dependency>
	</dependencies>
</project>
