############################################
###       APPLICATION PARAMETERS         ###
############################################

spring.main.web-application-type=NONE

service.registry.address=127.0.0.1
service.registry.port=8443

# path to db file may change
spring.datasource.url=jdbc:sqlite:experiment.db
spring.datasource.username=qos
spring.datasource.password=qos
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
# use true only for debugging
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

mqtt.broker.address=127.0.0.1
#mqtt.broker.port=1883
mqtt.broker.port=4763
mqtt.client.password=123456


############################################
###          CUSTOM PARAMETERS           ###
############################################

# Address to register into Service Registry with
domain.name=127.0.0.1

# The name of the system. 
system.name=CpuTestConsumer

test.comment="Experiment 1"

# Use Quality of Service evaluator during orchestration 
test.qos.enabled=false

# Metrics used in QoS evaluator
test.qos.metric.names=CPU_TOTAL_LOAD_MEAN

# Weight of the corresponding metric
test.qos.metric.weights=1

# Time window used in QoS evaluator in seconds
test.qos.time.window=1 

# Number of orchestrations and service consumptions
test.iteration=10

# Waiting between two  orchestrations and service consumptions pair in ms
test.wait=1000

# Test CPU load in percent
test.cpu.stress.power=20

# The length of the CPU stress test in ms
test.cpu.stress.length=5000 

# Requests that does not return before the threshold are considered as unsuccessful (ms) 
test.timeout.threshold=15000