############################################
###       APPLICATION PARAMETERS         ###
############################################

spring.main.web-application-type=NONE

service.registry.address=127.0.0.1
service.registry.port=8443

# path to db file may change
spring.datasource.url=jdbc:sqlite:experiment.db
spring.datasource.username=qos
spring.datasource.password=qos
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
# use true only for debugging
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

mqtt.broker.address=127.0.0.1
#mqtt.broker.port=1883
mqtt.broker.port=4763
mqtt.client.password=123456


############################################
###          CUSTOM PARAMETERS           ###
############################################

# Address to register into Service Registry with
domain.name=127.0.0.1

# The name of the system. 
system.name=CpuTestConsumer