############################################
###       APPLICATION PARAMETERS         ###
############################################

spring.main.web-application-type=NONE

service.registry.address=127.0.0.1
service.registry.port=8443

# path to db file may change
spring.datasource.url=jdbc:sqlite:experiment.db
spring.datasource.username=qos
spring.datasource.password=qos
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
# use true only for debugging
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


############################################
###          CUSTOM PARAMETERS           ###
############################################

# Address to register into Service Registry with
domain.name=127.0.0.1

# The name of the system. 
system.name=CpuTestConsumer

# Method to authenticate service requester systems
authentication.policy=declared

# Credentials to login to the authentication servers when authentication policy is 'outsourced'.
# The cloud operator need to register this system to this system to the Authentication Core system and fill the password field with the actual password before starting this system.
# authenticator.credentials={\
#  	'password': '123456' \
# }